services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cronicus
      POSTGRES_PASSWORD: CronNeedsMoreMONEY
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cronicus -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    image: golang:1.25.4-alpine
    container_name: go-server
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: sh -c "go mod download && go run main.go"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cronicus
      DB_PASSWORD: CronNeedsMoreMONEY
      DB_NAME: appdb
      JWT_SECRET: SuperSecretJWTKey123!

volumes:
  postgres_data:
